language: python
python:
- 2.7
- 3.4
before_install:
- pip install -r requires/testing.txt
- pip install codecov
install:
- pip install -e .
script: nosetests --with-coverage
after_success:
- codecov
sudo: false
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  on:
    python: 3.4
    tags: true
    all_branches: true
  user: sprockets
